
-- routines_setup_clean.sql
-- Digital Routines System for Iron Body
-- VERSION LIMPIEZA TOTAL (Clean Slate)

-- PRECAUCIÓN: Elimina tablas existentes para corregir errores de permisos
DROP TABLE IF EXISTS public.workout_exercises;
DROP TABLE IF EXISTS public.workout_logs;
DROP TABLE IF EXISTS public.user_routine_schedule;
DROP TABLE IF EXISTS public.routine_exercises;
DROP TABLE IF EXISTS public.routines;
DROP TABLE IF EXISTS public.exercises;

-- 1. Exercises Catalog
CREATE TABLE public.exercises (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    muscle_group TEXT NOT NULL,          
    equipment TEXT DEFAULT 'bodyweight', 
    description TEXT,
    image_url TEXT,                      
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Routines (Templates and User-created)
CREATE TABLE public.routines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    difficulty TEXT DEFAULT 'intermediate', 
    goal TEXT DEFAULT 'hypertrophy',         
    estimated_duration INT DEFAULT 60,       
    is_template BOOLEAN DEFAULT FALSE,       
    created_by UUID REFERENCES auth.users(id),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Routine Exercises (Joining table)
CREATE TABLE public.routine_exercises (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    routine_id BIGINT REFERENCES public.routines(id) ON DELETE CASCADE,
    exercise_id BIGINT REFERENCES public.exercises(id),
    order_index INT NOT NULL,
    sets INT DEFAULT 3,
    reps TEXT DEFAULT '10',            
    rest_seconds INT DEFAULT 90,
    suggested_weight TEXT,              
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Routine Schedule (Mapping routines to days of the week)
CREATE TABLE public.user_routine_schedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    routine_id BIGINT REFERENCES public.routines(id) ON DELETE CASCADE,
    day_of_week INT NOT NULL,           
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, day_of_week)        
);

-- 5. Workout Logs (Completed sessions)
CREATE TABLE public.workout_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    routine_id BIGINT REFERENCES public.routines(id),
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ,
    duration_seconds INT,
    total_volume NUMERIC DEFAULT 0,    
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Workout Exercises (Exercise details per log)
CREATE TABLE public.workout_exercises (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_log_id BIGINT REFERENCES public.workout_logs(id) ON DELETE CASCADE,
    exercise_id BIGINT REFERENCES public.exercises(id),
    sets_completed JSONB NOT NULL,
    order_index INT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.exercises ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.routines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.routine_exercises ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_routine_schedule ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workout_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workout_exercises ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Everyone can see exercises" ON public.exercises FOR SELECT TO authenticated USING (true);

CREATE POLICY "Users can see templates and their own routines" ON public.routines 
FOR SELECT TO authenticated USING (is_template = true OR created_by = auth.uid());

CREATE POLICY "Users can create their own routines" ON public.routines 
FOR INSERT TO authenticated WITH CHECK (created_by = auth.uid());

CREATE POLICY "Users can edit their own routines" ON public.routines 
FOR UPDATE TO authenticated USING (created_by = auth.uid());

CREATE POLICY "Users can see their routine exercises" ON public.routine_exercises 
FOR SELECT TO authenticated USING (
    EXISTS (SELECT 1 FROM public.routines r WHERE r.id = routine_id AND (r.is_template = true OR r.created_by = auth.uid()))
);

CREATE POLICY "Users manage their own routine exercises" ON public.routine_exercises 
FOR ALL TO authenticated USING (
    EXISTS (SELECT 1 FROM public.routines r WHERE r.id = routine_id AND r.created_by = auth.uid())
);

CREATE POLICY "Users manage their own schedule" ON public.user_routine_schedule 
FOR ALL TO authenticated USING (user_id = auth.uid());

CREATE POLICY "Users see their own logs" ON public.workout_logs 
FOR SELECT TO authenticated USING (user_id = auth.uid());

CREATE POLICY "Users create their own logs" ON public.workout_logs 
FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());

CREATE POLICY "Users see their own workout exercise details" ON public.workout_exercises 
FOR SELECT TO authenticated USING (
    EXISTS (SELECT 1 FROM public.workout_logs wl WHERE wl.id = workout_log_id AND wl.user_id = auth.uid())
);

CREATE POLICY "Users create their own workout exercise details" ON public.workout_exercises 
FOR INSERT TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM public.workout_logs wl WHERE wl.id = workout_log_id AND wl.user_id = auth.uid())
);

-- Indexing for performance
CREATE INDEX idx_routines_created_by ON public.routines(created_by);
CREATE INDEX idx_routine_exercises_routine_id ON public.routine_exercises(routine_id);
CREATE INDEX idx_user_routine_schedule_user_id ON public.user_routine_schedule(user_id);
CREATE INDEX idx_workout_logs_user_id ON public.workout_logs(user_id);
CREATE INDEX idx_workout_exercises_log_id ON public.workout_exercises(workout_log_id);
