-- ─── weight_logs: body weight history ────────────────────────────────────────
--
-- user_stats.weight only ever holds the LATEST value — every edit overwrites
-- it, so there was no way to show weight over time. This table is an
-- append-only log the client writes to alongside the user_stats upsert (see
-- NutritionAPI.saveUserStats / app/(tabs)/nutrition.tsx's handleSaveStats),
-- so a weight history builds up for free every time the user updates their
-- stats — no separate "log my weight" action required.

CREATE TABLE IF NOT EXISTS public.weight_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  weight NUMERIC NOT NULL,
  logged_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_weight_logs_user_id ON public.weight_logs(user_id, logged_at DESC);

ALTER TABLE public.weight_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users manage their own weight logs" ON public.weight_logs;
CREATE POLICY "Users manage their own weight logs" ON public.weight_logs
FOR ALL TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
