-- gamification_v5.sql
-- 1. Tabla de Historial (Log de Puntos)
create table if not exists public.gamification_logs (
  id bigint generated by default as identity primary key,
  user_id text not null, -- Referencia al ID de Auth (en profiles)
  action_type text not null,
  points int not null,
  metadata text,
  created_at timestamp with time zone default now()
);

-- 2. Tabla de QRs Dinámicos
create table if not exists public.generated_qrs (
  id uuid primary key default gen_random_uuid(),
  action_type text not null,
  points_value int not null,
  created_by text,
  is_used boolean default false,
  created_at timestamp default now()
);

-- 3. Asegurar RLS en las nuevas tablas
alter table public.gamification_logs enable row level security;
alter table public.generated_qrs enable row level security;

drop policy if exists "Ver mis logs" on public.gamification_logs;
drop policy if exists "Admin crea QRs" on public.generated_qrs;
drop policy if exists "Todos leen QRs" on public.generated_qrs;

create policy "Ver mis logs" on public.gamification_logs 
for select using (auth.uid()::text = user_id);

create policy "Admin crea QRs" on public.generated_qrs 
for insert with check (auth.uid()::text in (select email from public.profiles where role = 'ADMIN')); -- Ajustado si el role está en profiles

create policy "Todos leen QRs" on public.generated_qrs 
for select using (true);

-- 4. Actualizar Trigger para manejar la tabla 'profiles' correctamente
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER 
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Insert/Update en la tabla profiles (la nueva estructura del usuario)
  INSERT INTO public.profiles (
    email,
    username,
    phone,
    role,
    status,
    total_points,
    created_at,
    updated_at
  )
  VALUES (
    new.email,
    new.raw_user_meta_data->>'first_name', -- Se usa firstName como username inicial
    new.raw_user_meta_data->>'phone',
    'CLIENT',
    'ACTIVE',
    0,
    now(),
    now()
  )
  ON CONFLICT (email) DO UPDATE SET
    username = EXCLUDED.username,
    phone = EXCLUDED.phone,
    updated_at = now();

  RETURN new;
END;
$$ LANGUAGE plpgsql;

-- 5. Función Maestra de Escaneo para 'profiles'
create or replace function process_qr_scan(qr_code text)
returns json
language plpgsql
security definer
as $$
declare
  u_email text;
  points_to_add int;
  qr_record record;
begin
  -- Obtenemos el email del usuario autenticado (llave en profiles)
  select email into u_email from auth.users where id = auth.uid();

  -- QRs ESTÁTICOS
  if qr_code = 'GYM_STATIC_ATTENDANCE_KEY' then
    if exists (select 1 from gamification_logs where user_id = auth.uid()::text and action_type = 'ATTENDANCE' and created_at > current_date) then
      return '{"success": false, "message": "Ya marcaste asistencia hoy"}'::json;
    end if;
    insert into gamification_logs (user_id, action_type, points) values (auth.uid()::text, 'ATTENDANCE', 50);
    update profiles set total_points = coalesce(total_points, 0) + 50 where email = u_email;
    return '{"success": true, "message": "Asistencia registrada (+50 pts)"}'::json;
  end if;

  if qr_code = 'GYM_STATIC_WORKOUT_KEY' then
    if exists (select 1 from gamification_logs where user_id = auth.uid()::text and action_type = 'WORKOUT' and created_at > current_date) then
      return '{"success": false, "message": "Ya registraste tu rutina hoy"}'::json;
    end if;
    insert into gamification_logs (user_id, action_type, points) values (auth.uid()::text, 'WORKOUT', 30);
    update profiles set total_points = coalesce(total_points, 0) + 30 where email = u_email;
    return '{"success": true, "message": "Entrenamiento completado (+30 pts)"}'::json;
  end if;

  -- QRs DINÁMICOS
  begin
    select * into qr_record from public.generated_qrs where id = qr_code::uuid;
    if not found then return '{"success": false, "message": "Código QR no válido"}'::json; end if;
    if qr_record.is_used then return '{"success": false, "message": "Este código ya fue utilizado"}'::json; end if;
    
    points_to_add := qr_record.points_value;
    update public.generated_qrs set is_used = true where id = qr_record.id;
    insert into gamification_logs (user_id, action_type, points) values (auth.uid()::text, qr_record.action_type, points_to_add);
    update profiles set total_points = coalesce(total_points, 0) + points_to_add where email = u_email;
    
    return json_build_object('success', true, 'message', 'Puntos canjeados: ' || points_to_add);
  exception when others then
    return '{"success": false, "message": "Error procesando QR o ID inválido"}'::json;
  end;
end;
$$;
