
-- gamification_schema_final.sql
-- Este script recrea toda el área de gamificación asegurando que el dueño sea postgres

-- 1. Tabla de Logs (Historial de puntos)
CREATE TABLE IF NOT EXISTS public.gamification_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    action_type TEXT NOT NULL,
    points INT NOT NULL,
    metadata TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.gamification_logs OWNER TO postgres;

-- 2. Tabla de QRs Dinámicos (Para cupones de un solo uso)
CREATE TABLE IF NOT EXISTS public.generated_qrs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    action_type TEXT NOT NULL,
    points_value INT NOT NULL,
    created_by UUID REFERENCES auth.users(id),
    is_used BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.generated_qrs OWNER TO postgres;

-- 3. Tabla de Ranking (Resumen de puntos para carga rápida)
CREATE TABLE IF NOT EXISTS public.leaderboard_entries (
    id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
    score INT DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE public.leaderboard_entries OWNER TO postgres;

-- 4. Habilitar RLS en todas las tablas
ALTER TABLE public.gamification_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.generated_qrs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leaderboard_entries ENABLE ROW LEVEL SECURITY;

-- Políticas de Seguridad
DROP POLICY IF EXISTS "Usuarios ven sus propios logs" ON public.gamification_logs;
CREATE POLICY "Usuarios ven sus propios logs" ON public.gamification_logs
    FOR SELECT TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Todos ven el ranking" ON public.leaderboard_entries;
CREATE POLICY "Todos ven el ranking" ON public.leaderboard_entries
    FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Admin gestiona QRs" ON public.generated_qrs;
CREATE POLICY "Admin crea QRs" ON public.generated_qrs
    FOR ALL TO authenticated USING (
        EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'ADMIN')
    );

-- 5. Función Maestra de Sincronización (Profiles -> Leaderboard)
CREATE OR REPLACE FUNCTION public.sync_profile_to_leaderboard()
RETURNS TRIGGER 
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    INSERT INTO public.leaderboard_entries (id, score, updated_at)
    VALUES (NEW.id, NEW.total_points, NOW())
    ON CONFLICT (id) DO UPDATE SET
        score = EXCLUDED.score,
        updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
ALTER FUNCTION public.sync_profile_to_leaderboard() OWNER TO postgres;

-- Trigger para sincronización
DROP TRIGGER IF EXISTS tr_sync_leaderboard ON public.profiles;
CREATE TRIGGER tr_sync_leaderboard
    AFTER INSERT OR UPDATE OF total_points ON public.profiles
    FOR EACH ROW EXECUTE FUNCTION public.sync_profile_to_leaderboard();

-- 6. Función Maestra de Escaneo de QR
CREATE OR REPLACE FUNCTION public.process_qr_scan(qr_code text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_clean_qr text;
  v_points int;
  v_action text;
BEGIN
  v_clean_qr := trim(qr_code);

  -- LÓGICA DE QRs ESTÁTICOS
  IF v_clean_qr LIKE 'GYM_STATIC_ATTENDANCE_KEY%' THEN
    v_action := 'ATTENDANCE';
    v_points := 50;
  ELSIF v_clean_qr LIKE 'GYM_STATIC_WORKOUT_KEY%' THEN
    v_action := 'WORKOUT';
    v_points := 30;
  ELSE
    -- LÓGICA DE QRs DINÁMICOS
    BEGIN
      IF v_clean_qr ~ '^[0-9a-fA-F-]{36}$' THEN
        SELECT action_type, points_value INTO v_action, v_points 
        FROM public.generated_qrs 
        WHERE id = v_clean_qr::uuid AND is_used = FALSE;
        
        IF NOT FOUND THEN RETURN '{"success": false, "message": "Código inválido o ya usado"}'::json; END IF;
        UPDATE public.generated_qrs SET is_used = TRUE WHERE id = v_clean_qr::uuid;
      ELSE
        RETURN '{"success": false, "message": "Formato de código no reconocido"}'::json;
      END IF;
    END;
  END IF;

  -- Aplicar puntos si no se ha hecho hoy (para estáticos)
  IF v_action IN ('ATTENDANCE', 'WORKOUT') AND EXISTS (
      SELECT 1 FROM public.gamification_logs 
      WHERE user_id = auth.uid() AND action_type = v_action AND created_at > CURRENT_DATE
  ) THEN
    RETURN json_build_object('success', false, 'message', 'Ya registraste ' || v_action || ' hoy');
  END IF;

  -- Insertar log y actualizar puntos en perfil
  INSERT INTO public.gamification_logs (user_id, action_type, points) 
  VALUES (auth.uid(), v_action, v_points);

  UPDATE public.profiles 
  SET total_points = COALESCE(total_points, 0) + v_points,
      updated_at = NOW()
  WHERE id = auth.uid();

  RETURN json_build_object('success', true, 'message', '¡Éxito! Ganas +' || v_points || ' pts');
END;
$$;
ALTER FUNCTION public.process_qr_scan(text) OWNER TO postgres;

-- 7. Carga inicial de ranking basada en puntos actuales
INSERT INTO public.leaderboard_entries (id, score, updated_at)
SELECT id, total_points, updated_at FROM public.profiles WHERE total_points > 0
ON CONFLICT (id) DO UPDATE SET score = EXCLUDED.score, updated_at = NOW();
