-- Run this SQL in your Supabase SQL Editor to create the necessary tables for the Nutrition feature.

-- Table: user_stats
create table if not exists public.user_stats (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) not null,
  weight numeric not null,
  height numeric not null,
  age int,
  gender text,
  activity_level text,
  goal text,
  allergies text[],
  updated_at timestamp with time zone default now(),
  constraint unique_user_stats unique (user_id)
);

alter table public.user_stats enable row level security;

do $$
begin
    if not exists (select 1 from pg_policies where policyname = 'Mis stats' and tablename = 'user_stats') then
        create policy "Mis stats" on public.user_stats for all using ( auth.uid() = user_id );
    end if;
end
$$;

-- Table: diet_plans
create table if not exists public.diet_plans (
  id bigint generated by default as identity primary key,
  name text,
  calories int,
  macros jsonb,
  meals jsonb,
  created_by uuid references auth.users(id)
);

alter table public.diet_plans enable row level security;

do $$
begin
    if not exists (select 1 from pg_policies where policyname = 'Ver dietas' and tablename = 'diet_plans') then
        create policy "Ver dietas" on public.diet_plans for select using ( true );
    end if;
end
$$;

-- Table: user_diets
create table if not exists public.user_diets (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id),
  diet_plan_id bigint references public.diet_plans(id),
  assigned_at timestamp with time zone default now(),
  active boolean default true
);

alter table public.user_diets enable row level security;

do $$
begin
    if not exists (select 1 from pg_policies where policyname = 'Mi dieta' and tablename = 'user_diets') then
        create policy "Mi dieta" on public.user_diets for select using ( auth.uid() = user_id );
    end if;
end
$$;
